export enum MedicalSpecialty {
    // Chuyen khoa
    Co_Xuong_Khop = 'Cơ Xương Khớp',
    Than_Kinh = 'Thần kinh',
    Tieu_Hoa = 'Tiêu hoá',
    Tim_Mach = 'Tim mạch',
    Tai_Mui_Hong = 'Tai Mũi Họng',
    Cot_Song = 'Cột sống',
    Y_Hoc_Co_Truyen = 'Y học Cổ truyền',
    Cham_Cuu = 'Châm cứu',
    San_Phu_khoa = 'Sản Phụ khoa',
    Sieu_Am_Thai = 'Siêu âm thai',
    Nhi_Khoa = 'Nhi khoa',
    Da_Lieu = 'Da liễu',
    Benh_Viem_Gan = 'Bệnh Viêm gan',
    Suc_Khoe_Tam_Than = 'Sức khỏe tâm thần',
    Di_Ung_Mien_Dich = 'Dị ứng miễn dịch',
    Ho_Hap_Phoi = 'Hô hấp - Phổi',
    Ngoai_Than_Kinh = 'Ngoại thần kinh',
    Nam_Hoc = 'Nam học',
    Chuyen_Khoa_Mat = 'Chuyên khoa Mắt',
    Than_Tiet_Nieu = 'Thận - Tiết niệu',
    Noi_Khoa = 'Nội khoa',
    Nha_Khoa = 'Nha khoa',
    Tieu_Duong_Noi_Tiet = 'Tiểu đường - Nội tiết',
    Phuc_Hoi_Chuc_Nang = 'Phục hồi chức năng',
    Chup_Cong_Huong_Tu = 'Chụp Cộng hưởng từ',
    Chup_Cat_Lop_Vi_Tinh = 'Chụp cắt lớp vi tính',
    Noi_Soi_Tieu_Hoa = 'Nội soi Tiêu hóa',
    Ung_Buou = 'Ung bướu',
    Da_Lieu_Tham_My = 'Da liễu thẩm mỹ',
    Truyen_Nhiem = 'Truyền nhiễm',
    Bac_Si_Gia_Dinh = 'Bác sĩ gia đình',
    Tao_Hinh_Ham_Mat = 'Tạo hình Hàm Mặt',
    Tu_van_tri_lieu_Tam_ly = 'Tư vấn, trị liệu Tâm lý',
    Vo_Sinh_Hiem_Muon = 'Vô sinh - Hiếm muộn',
    Chan_Thuong_Chinh_Hinh = 'Chấn thương chỉnh hình',
    Nieng_Rang = 'Niềng răng',
    Boc_Rang_Su = 'Bọc răng sứ',
    Trong_Rang_Implant = 'Trồng răng implant',
    Nho_Rang_Khon = 'Nhổ răng khôn',
    Nha_Khoa_Tong_Quat = 'Nha khoa tổng quát',
    Nha_Khoa_Tre_Em = 'Nha khoa trẻ em',
    Tuyen_Giap = 'Tuyến giáp',

    //Kham tu xa
    Tu_Van_Tri_Lieu_Tam_Ly_Tu_Xa = 'Tư vấn, trị liệu Tâm lý từ xa',
    Suc_Khoe_Tam_Than_Tu_Xa = 'Sức khỏe tâm thần từ xa',
    Bac_Si_Da_Lieu_Tu_Xa = 'Bác sĩ Da liễu từ xa',
    Bac_Si_Co_Xuong_Khop_Tu_Xa = 'Bác sĩ Cơ-Xương-Khớp từ xa',
    Bac_Si_Tieu_Hoa_Tu_Xa = 'Bác sĩ Tiêu hóa từ xa',
    Bac_Si_Noi_Khoa_Tu_Xa = 'Bác sĩ Nội khoa từ xa',
    Bac_Si_San_Phu_Khoa_Tu_Xa = 'Bác sĩ Sản phụ khoa từ xa',
    Bac_Si_Tim_Mach_Tu_Xa = 'Bác sĩ Tim mạch từ xa',
    Bac_Si_Nhi_Tu_Xa = 'Bác sĩ Nhi từ xa',
    Bac_Si_Tai_Mui_Hong_Tu_Xa = 'Bác sĩ Tai-Mũi-Họng từ xa',
    Bac_Si_Than_Kinh_Tu_Xa = 'Bác sĩ Thần kinh từ xa',
    Bac_Si_Tu_Van_F0 = 'Bác sĩ tư vấn F0',

    // Kham tong quat
    Co_Ban = 'Cơ bản',
    Goi_Kham_VIP = 'Gói khám VIP',
    Nang_Cao = 'Nâng cao',
    Nam = 'Nam',
    Nu = 'Nữ',
    Tre_Em = 'Trẻ em',
    Nguoi_Gia = 'Người già',
    Tien_Hon_Nhan = 'Tiền hôn nhân',
    Tam_Soat_Ung_Thu = 'Tầm soát ung thư',
    Tam_Soat_Ung_Thu_Vu = 'Tầm soát ung thư vú',
    Tam_Soat_Tieu_Hoa = 'Tầm soát tiêu hóa',
    Benh_Ly_Chung = 'Bệnh lý chung',

    // Xet nghiem y hoc
    Tong_Quat = 'Tổng quát',
    Tai_Nha = 'Tại nhà',
    Ung_Thu = 'Ung thư',
    NIPT = 'NIPT',
    Sot_Xuat_Huyet = 'Sốt xuất huyết',
    Di_Ung = 'Dị ứng',
    Gan = 'Gan',
    Cum_Va_Sot = 'Cúm và Sốt',
    Covid = 'Covid',
    Gen = 'Gen',

    // Suc khoe tinh than
    // duplicate
    // Suc_Khoe_Tam_Than = 'Sức khỏe tâm thần',
    // Tu_Van_Tri_Lieu_Tam_Ly_Tu_Xa = 'Tư vấn, trị liệu Tâm lý từ xa',
    // Suc_Khoe_Tam_Than_Tu_Xa = 'Sức khỏe tâm thần từ xa',
    Tu_Van_Tri_Lieu_Tam_Ly = 'Tư vấn, trị liệu Tâm lý',

    // Kham nha khoa
    // duplicate
    // Nha_Khoa = 'Nha khoa',
    // Nieng_Rang = 'Niềng răng',
    // Boc_Rang_Su = 'Bọc răng sứ',
    // Trong_Rang_Implant = 'Trồng răng implant',
    // Nho_Rang_Khon = 'Nhổ răng khôn',
    // Nha_Khoa_Tong_Quat = 'Nha khoa tổng quát',
    // Nha_Khoa_Tre_Em = 'Nha khoa trẻ em',

    // Goi phau thuat
    Phau_Thuat_Nam_Hoc = 'Phẫu thuật Nam học',
    Phau_Thuat_Than_Tiet_Nieu = 'Phẫu thuật Thận - Tiết niệu',
    Phau_Thuat_Tai_Mui_Hong = 'Phẫu thuật Tai -Mũi - Họng',
    Phau_Thuat_Hau_Mon_Truc_Trang = 'Phẫu thuật Hậu môn - Trực tràng',
    Phau_Thuat_Mat = 'Phẫu thuật mắt',
    Thu_Thuat_Suy_Gian_Tinh_Mach = 'Thủ thuật Suy giãn tĩnh mạch',
}
